######################################################################
# Automatically generated by qmake (3.0) Fr 27. Apr 12:01:22 2018
######################################################################

TEMPLATE = app
TARGET = BHYWI-22-E1
INCLUDEPATH += C:\User\2_TUD\LEHRE\19_SoSe2018\BHYWI-22\EXERCISES\BHYWI-22-E1-2018

QT += widgets #new

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp solver.cpp
